services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  QOne\PrivacyBundle\Command\ObsolescenceCommand:
    arguments:
      - '@QOne\PrivacyBundle\Manager\PrivacyManagerInterface'
      - '@QOne\PrivacyBundle\Mapping\MetadataRegistryInterface'
      - '%qone_privacy.persistence.object_managers.asset%'
    calls:
      - method: setContainer
        arguments: ['@service_container']
    tags: ['console.command']

  QOne\PrivacyBundle\Command\LegacyCommand:
    arguments:
      - '@QOne\PrivacyBundle\Manager\PrivacyManagerInterface'
      - '%qone_privacy.persistence.object_managers.asset%'
    calls:
      - method: setContainer
        arguments: ['@service_container']
    tags: ['console.command']
