services:
  _defaults:
    public: true
    autowire: false
    autoconfigure: false

  qone_privacy.delivery.local_delivery:
    class: QOne\PrivacyBundle\Delivery\LocalDelivery
    arguments:
      - '@QOne\PrivacyBundle\Manager\PublisherInterface'
