services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: true

  QOne\PrivacyBundle\Policy\NullPolicy:
    arguments:
      - '@doctrine'
      - '@QOne\PrivacyBundle\Mapping\MetadataRegistryInterface'
  QOne\PrivacyBundle\Policy\RemovePolicy:
    arguments:
      - '@doctrine'
      - '@QOne\PrivacyBundle\Mapping\MetadataRegistryInterface'
  QOne\PrivacyBundle\Policy\TruncatePolicy:
    arguments:
      - '@doctrine'
      - '@QOne\PrivacyBundle\Mapping\MetadataRegistryInterface'